Traceback (most recent call last):
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# How to use Pytorch
import torch

# We can initialize a matrix as a pytorch tensor:
A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) 
print('A is', A)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# How to use Pytorch[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mtorch[39;00m
[1;32m      4[0m [38;5;66;03m# We can initialize a matrix as a pytorch tensor:[39;00m
[1;32m      5[0m A [38;5;241m=[39m torch[38;5;241m.[39mtensor([[[38;5;241m1[39m,[38;5;241m2[39m,[38;5;241m3[39m],[[38;5;241m4[39m,[38;5;241m5[39m,[38;5;241m6[39m],[[38;5;241m7[39m,[38;5;241m8[39m,[38;5;241m9[39m]]) 

[0;31mModuleNotFoundError[0m: No module named 'torch'
ModuleNotFoundError: No module named 'torch'

